### ISSUE TITLE
problem with pack if the file is bigger than 8G

### ISSUE THREAD

**Issue by wendy0911** [mafintosh/tar-fs#100]
It working only for file less than 8GB when is packing.
the file folder includes one file more than 8GB such as 9GB, packing is success, but the tar is corrupt and the size is smaller

**Comment by wendy0911** [comment]
modified tar-stream header.js from buf.write(encodeOct(opts.size, 11), 124) to buf.write(encodeOct(opts.size, 12), 124)
then it supports 64GB ，Octal 777777777777

**Comment by mafintosh** [comment]
Did you get it working? The extended headers should work here

**Comment by wendy0911** [comment]
> Did you get it working? The extended headers should work here

yes, It worked after I modified tar-stream header.js from buf.write(encodeOct(opts.size, 11), 124) to buf.write(encodeOct(opts.size, 12), 124) . but I don't know how to use extended headers to solve this issue?
