### ISSUE TITLE
some .bin file can not be packed in tar(windows system)

### ISSUE THREAD

**Issue by wendy0911** [mafintosh/tar-fs#105]
please decompress the contents of the attachment, the file test.bin can't be packed in the tar..
[test.bin.zip](https://github.com/mafintosh/tar-fs/files/11459319/test.bin.zip)

the code is as bellow:

 var w = fs.createWriteStream("my.tar")
 tar.pack("c://my-directory'").pipe(w)    // my-directory included test.bin file

how can I package this file successfully?

**Comment by mafintosh** [comment]
try on latest major, reopen if still an issue

**Comment by wendy0911** [comment]
it is still not worked for me ! please refer to the attachment
[binsfiles.zip](https://github.com/mafintosh/tar-fs/files/11798220/binsfiles.zip)
