### ISSUE TITLE
No option to follow symlinks in packing function

### ISSUE THREAD

**Issue by gsikorski** [mafintosh/tar-fs#14]
Linux standard tar command includes command line switch allowing to follow symlinks. Would be great to add this as an option to this module. My project requires to archive quite a lot of data 'on the fly' and pass output stream directly to HTTP socket. Some of files ar big and copy would be inefficient, that is why they are symbolic links.

**Comment by mafintosh** [comment]
tar-fs 1.5.0 now contains a `dereference` option that when set to `true` follows symlinks

**Comment by gsikorski** [comment]
Thanks, that was really fast :)

**Comment by quocvu** [comment]
In my case, I would like to keep symlinks in my tarball (do not dereference) but the top level folder is a symlink.  For example this is my file structure

```
/var/data/myapp/2016-03-10/
  - file1
  - file2
  - symlink1
  - folder1
/var/data/myapp/current -> 2016-03-10
```

My I run `tar.pack('/var/data/myapp/current').pipe(fs.createWriteStream(/var/archive.tar))` I would like to get the entire content of the folder `/var/data/myapp/2016-03-10/` with symlink1 staying as a symlink.

Is it possible?
Thanks
