### ISSUE TITLE
Error: EPERM, utime 

### ISSUE THREAD

**Issue by majidgolshadi** [mafintosh/tar-fs#17]
I use this package in my app to compress some folder content. as you said

``` javascript
tar.pack(source).pipe(fs.createWriteStream(fullAddress)); 
// source = folder address
// fullAddress = tar file destination
```

After call it tar file created and everything is ok but when i try to uncompressed that file

``` javascript
fs.createReadStream(TarFile).pipe(tar.extract(destinationFolder));
```

 I got this error

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, utime '/code/' <-------------- destination address
31 May 05:42:48 - [nodemon] app crashed - waiting for file changes before starting...
```

Code folder permission is 777
Why this happen and how can i solve it?

**Comment by mafintosh** [comment]
do you have permission to write in that folder?

**Comment by majidgolshadi** [comment]
Yes. 
As i explained above. the folder permission was 777.
