### ISSUE TITLE
Errors with illegal characters on windows

### ISSUE THREAD

**Issue by sebakerckhof** [mafintosh/tar-fs#18]
Hello,

I have a tar file that contains a folder with a colon in it's name. In windows this is an illegal character and tar-fs seems to hang on it.
Usually most utilities, like 7z will convert colons to underscores....

**Comment by mafintosh** [comment]
I'd merge a PR that fixes this :)

**Comment by sindresorhus** [comment]
You might want to use something like https://github.com/sindresorhus/filenamify as there are more illegal characters.

**Comment by mafintosh** [comment]
@sindresorhus does that work with absolute paths?

**Comment by sindresorhus** [comment]
No, since it supports fixing filenames that are `foo/bar`. I've added an extra method for handling paths as input: https://github.com/sindresorhus/filenamify#filenamifypathinput-options

Alternatively you could use: https://github.com/sindresorhus/filename-reserved-regex
