### ISSUE TITLE
Can not pack if the script doing the pack is included in the files to pack

### ISSUE THREAD

**Issue by cgadam** [mafintosh/tar-fs#22]
The "pack" action is not working for this scenario:

- Folder to pack: sourceCodeFolder
- Script that performs the pack: sourceCodeFolder/scripts/pack.js
- Output folder: sourceCodeFolder/../packed.zip (outside sourceCodeFolder)

I think it should work fine even if some files are being used inside sourceCodeFolder as it should only require read access to the files being packed. 

The pack process does not fail. The result is a zero bytes .tar file. If I double click it (in Mac at least) the Archive Utility extracts another file with exact same name but with .cpgz extension. If I now try to open this .cpgz file I end up once again with a .tar file with the same name (with a " 2" added to the file's name due to duplication). This turns into an infinite loop if you want to uncompress .tar and then uncompress .cpgz over and over again.

**Comment by mafintosh** [comment]
could you share the complete script?

**Comment by cgadam** [comment]
Well, I tried this in isolation and it is working fine :(
http://expirebox.com/download/1a99333729f0ecd8cad9ca854953582e.html
Is there any log I can enable to see why this is happening for another considerably big folder I'm trying to tar?

**Comment by mafintosh** [comment]
hmm no but we should add [debug](https://github.com/visionmedia/debug). feel free to send a pr with that
