### ISSUE TITLE
How to know when tar.pack is done?

### ISSUE THREAD

**Issue by Coaxial** [mafintosh/tar-fs#23]
I can't seem to find how to know when `tar.pack` is done so I can call the callback.

I have
```javascript
function tarMyDir(done) {
  tar.pack('my-dir')
    .pipe(fs.createWriteStream('my-file.tar'))
    .on('error', done)
    .on('end', done);
}
```

But the `done` callback is never ever called. If I listen for `finish` instead of `end`, it makes no difference. What am I missing?

**Comment by mafintosh** [comment]
it should be finish instead of end which fires the cb if i run your example. anything special about that directory?

**Comment by Coaxial** [comment]
Yes, the directory name was resolving to undefined. Thanks for your help, it got me digging a bit deeper into streams before I realized my mistake. 

On September 28, 2015 12:44:10 PM EDT, Mathias Buus <notifications@github.com> wrote:
>it should be finish instead of end which fires the cb if i run your
>example. anything special about that directory?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mafintosh/tar-fs/issues/23#issuecomment-143800414

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mafintosh** [comment]
:+1:
