### ISSUE TITLE
Is there a way to create a tar of a directory in a sync way?

### ISSUE THREAD

**Issue by gajus** [mafintosh/tar-fs#26]

**Comment by mafintosh** [comment]
No sorry. This only allow you create a tar using the async fs api. Whats your use case for doing it sync?

**Comment by gajus** [comment]
Developing a CLI program for builds. Using sync code makes it easier to reason, esp. given that `fs` and `fs-extra` allow all operations in sync mode.

**Comment by gajus** [comment]
Not a show stopper. Just a nice thing to have.

**Comment by mafintosh** [comment]
Ah I see. I don't think we're gonna support a sync api anytime soon as the stream api is also async and this module relies on tar-stream.

**Comment by gajus** [comment]
Cool. It works great. Just implemented https://github.com/gajus/bundle-dependencies.
