### ISSUE TITLE
stream events not triggering when installed in Linux systems

### ISSUE THREAD

**Issue by pravinraj** [mafintosh/tar-fs#28]
Hi,
Stream events like, 'data', 'end', 'error' events are not getting triggered while pipe operation in Linux systems. But the same events are triggering perfectly at Windows. Hence, kindly provide the solution this issue.

Thanks,
Pravin

**Comment by mafintosh** [comment]
Could you provide an example?

**Comment by pravinraj** [comment]
Hi,

Below is the code-snippet where I am uploading some .tar file with key as "tar_file" in rest service. Here all the stream events are getting listened in Windows but not in Linux systems. This is POST service listening at 3000.

var  connectRoute = require('connect-route'),
	connect = require('connect'),
	formidable = require('formidable');
	app = connect();
	var tar = require('tar-fs'),
		fs = require('fs');
 
app.use(connectRoute(function (router) {
	
 
	router.post('/home', function (req, res, next) {
	var form = new formidable.IncomingForm();
    //form.encoding = webConfig.getConfigValues("file_download_encoding");
    
    form.parse(req, function (err, fields, files) {
		console.log(files.tar_file.path);
		 var tarstream = tar.extract('./unTar');
		 var tarread = fs.createReadStream(files.tar_file.path);
		  tarread.pipe(tarstream);
		 tarstream.on('data',function(data){
            console.log('inside data event');
        })
        tarstream.on('end', function (err) {
            console.log("Completed tar file creation -");
        });
        tarstream.on('error',function(err){
            console.log('Error!!!!!'+ err);
        });
       
	});
		res.end('POST to home');
	});
}));
 
app.listen(3000);

**Comment by mafintosh** [comment]
an extract stream never emits data or end since its a writable stream. you need to listen for `finish` to know when its done

**Comment by pravinraj** [comment]
Thanks mafintosh. It's working now. :)
