### ISSUE TITLE
By default, "." entry added

### ISSUE THREAD

**Issue by Chcap** [mafintosh/tar-fs#30]
When running on Linux system the pack example `tar.pack('./my-directory').pipe(fs.createWriteStream('my-tarball.tar'))`, the generated tar contains a "." entry.

> > tar -tf my-tarball.tar
> .
> my-file.txt
> another-file.txt

This entry should not be included.

**Comment by mafintosh** [comment]
Yea good point. I'm curious if this is actually breaking anything for you?

**Comment by Chcap** [comment]
No, not breaking, but it can be confusing for a user when finding a tar file with these strange "." entry. I agree, it is a minor issue :)

The workaround I used is to tar parent directory and to use my target directory as unique entry.

A solution would be, if no entries provided, to populate the queue with the list of files from readdir instead of single entry ".".

**Comment by bradchristensen** [comment]
Thanks for the workaround @Chcap! :smiley: My code now looks something like this:

```javascript
const fs = require('fs');
const { promisify } = require('util'); /* Note that this requires Node.js 8+ */
const tar = require('tar-fs');

const readdir = promisify(fs.readdir);

const entries = await readdir(tmpDirOutPath);
const tarStream = tar.pack(tmpDirOutPath, { entries });

/* Stream tarStream to somewhere, e.g. to a file:
 * tarStream.pipe(fs.createWriteStream('file.tar')); */
```

**Comment by knoxcard** [comment]
Close ticket?

**Comment by erikian** [comment]
Just dropped by to mention that I found that setting the `header.name` to an empty string on `map` also prevents the "." entry from being created:

```js
tar.pack('/path/to/directory', {
  map: header => {
    if (header.name === '.') {
      header.name = ''
    }

    return header
  },
})
```
