### ISSUE TITLE
Strange header type while packing

### ISSUE THREAD

**Issue by gautaz** [mafintosh/tar-fs#31]
Hello,

I wanted to use the header map option while packing in order to modify the header mode based on the header type.
Currently whatever the entry is (directory or file), the header given to the mapping function is always 'file'.

Looking at the [source code](https://github.com/mafintosh/tar-fs/blob/master/index.js#L98), it seems it cannot be something else.

Is that deliberate? Why is it so?

**Comment by mafintosh** [comment]
oh we should wait to call the mapper until the type has been populated.

here, https://github.com/mafintosh/tar-fs/blob/master/index.js#L107
here, https://github.com/mafintosh/tar-fs/blob/master/index.js#L113
and here, https://github.com/mafintosh/tar-fs/blob/master/index.js#L118

you wanna send a pr for that?

**Comment by gautaz** [comment]
@mafintosh done, the PR is #34
