### ISSUE TITLE
Invalid tar header

### ISSUE THREAD

**Issue by leejian1975** [mafintosh/tar-fs#40]
When we execute " fs.createReadStream('my-other-tarball.tar').pipe(tar.extract('./my-other-directory')) " ，the docker will occur an error.This error is  " Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?  ".

**Comment by renpillay** [comment]
I'm also seeing invalid tar headers when passing a tar-fs stream to dockerode.

**Comment by piranna** [comment]
This should be fixed in master, could you both confirm it?

**Comment by piranna** [comment]
I propose to close this, because should have been already fixed on `tar-stream`.
