### ISSUE TITLE
Doesn't work on windows 10

### ISSUE THREAD

**Issue by soichih** [mafintosh/tar-fs#41]
It doesn't seem to work on Windows 10.

I am piping .tar file from a web server into tar-fs.extract.

```
                   request.get({
                        url: config.api.core+"/resource/download",
                        json: true,
                        qs: {r: task.resource_id, p: instance._id+"/_thaw/"+path.basename(file.path)},
                        headers: auth_headers,
                    }).pipe(tar.extract(dirname))
```

I get following error message.

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: EISDIR: illegal operation on a directory, open 'C:\Users\Soichi\Desktop\Python-2.7.5.5717f7b43e583c602758d8e9\python'
    at Error (native)
```

I am using 

$ node --version
v4.2.6

**Comment by Zougi** [comment]
I doubt your error comes from windows10. I use tar-fs to untar packages similar to https://registry.npmjs.org/tar-fs/-/tar-fs-1.14.0.tgz and I had no problem so far. For my need though, a cache system, I download file entirely before extracting it
