### ISSUE TITLE
Create files if filesystem don't support hard-links

### ISSUE THREAD

**Issue by piranna** [mafintosh/tar-fs#43]
Vagrant, and more specifically VirtualBox and vboxfs, [don't allow to create hard-links](https://www.virtualbox.org/ticket/818), so I propose to add an option to create a new file if we get an `EPERM` when trying to extract a hard-link, so `prebuild` and `prebuild-install` modules could work correctly inside vagrant. I think the key line it's at https://github.com/mafintosh/tar-fs/blob/ebc956e5778f5023fe3170399b216a7ea6efac26/index.js#L250. Is there any objection about this?

**Comment by mafintosh** [comment]
as long as this is opt-in and relatively simple to do i'm +1

**Comment by piranna** [comment]
Fix is done on issue #44 and merged, clossing.
