### ISSUE TITLE
Error if and when the steam is not a valid tar file?

### ISSUE THREAD

**Issue by billxinli** [mafintosh/tar-fs#51]
Hi:

Curious why an error is not emitted on invalid tar files? 

`echo "this is just a plain text file" > file.tar`

```
var tarFs = require('tar-fs')
var fs = require('fs')

fs.createReadStream('./file.tar')
  .pipe(
    tarFs.extract('./test-o')
  )
  .on('error', function (err) {
    console.log(err);
  })
  .on('finish', function () {
    console.log('finished!');
  })
```

**Comment by mafintosh** [comment]
if will emit an error if the tar checksum fails but i guess your test file is too small (< 512b) so the header check never fires. we should fail is this case i agree.

**Comment by piranna** [comment]
Isn't this a bug on `tar-stream`? We should have a label for this ones...

**Comment by orsagie** [comment]
Hey, looks like you fixed this issue at least for node >= 8: https://github.com/mafintosh/tar-stream/commit/689d3fafd5def71a29610e9b0f2c5ff470a19a05

**Comment by mafintosh** [comment]
Should be fixed for all node actually
