### ISSUE TITLE
[Feature Request] Events / Callbacks

### ISSUE THREAD

**Issue by metrotyranno** [mafintosh/tar-fs#52]
Hi,

Would it be possible for some form of events or callbacks to be implemented, as far as I am aware I cannot execute tasks that are dependent on the write (extract) being finished.

**Comment by mafintosh** [comment]
you just need to wait for the `finish` event right now on extract streams and `end` on pack streams. these are just the normal stream events

``` js
var extract = tar.extract()

...

extract.on('finish', function () {
  // completely finished extracting the tar (all entry events flushed etc)
})
```

``` js
var pack = tar.pack()

...

pack.on('end', function () {
  // completely finished packing the tar
})
```

**Comment by mafintosh** [comment]
if you need something else feel free to re-open this issue

**Comment by matthewdolman** [comment]
Hi 

I just can't get this to work

``
const pack = tar.pack('/location/to/pack').pipe(fs.createWriteStream('tarname.tar'));
    
pack.on("end", function(){
    console.log("done")
});
``
