### ISSUE TITLE
Performance problems with concurrent unpacking?

### ISSUE THREAD

**Issue by victornoel** [mafintosh/tar-fs#61]
Hi,

In the https://github.com/yarnpkg/yarn project, we faced a strange problem both with node-tar and tar-fs during the unpacking of many stream at the same time.

The issue is yarnpkg/yarn#2629 and the interesting bit of information that led to this issue can be found starting with https://github.com/yarnpkg/yarn/issues/2629#issuecomment-283382353. The conclusion was that when yarn is downloading very very fast more than 12 (on one of the yarn dev machine, @bestander, than found the source of the issue) tar, because of the extreme concurrency, some of the extraction were failing at the filesystem level.

Originally tar-fs was tried as an alternative of the currently used node-tar, and the problem was visible as well with it. Yarn people are interested on using tar-fs and was wondering if you would help:
 - find a solution at tar-fs level to sustain this high throughput,
 - or find the underlying problem (if it is not directly a tar-fs problem) since you must understand the intricacies of node much better than many :)

I hope we can find a good solution together to improve the state of tar extraction in the node ecosystem :)
Thanks!

**Comment by bestander** [comment]
I think we could build a script to reproduce it that would download, unzip and untar [this file](https://registry.yarnpkg.com/@angular/core/-/core-4.0.0-rc.1.tgz) multiple times in parallel (20 threads).

**Comment by victornoel** [comment]
@mafintosh sorry to ping you, but would you have some time to give us feedback on this? I think yarn and its community would be really helped by it :)
Thanks!

**Comment by shinnn** [comment]
@victornoel Could you try passing [graceful-fs](https://github.com/isaacs/node-graceful-fs) to the undocumented [`fs`](https://github.com/mafintosh/tar-fs/blob/835bd4809d7a34a3924bcfc52df5f0a02d5aea9c/index.js#L172) option? I'm not sure this helps you, but [some features](https://github.com/isaacs/node-graceful-fs/tree/v4.1.11#improvements-over-fs-module) of graceful-fs seem to fit your use case.

**Comment by victornoel** [comment]
@shinnn thanks for the idea!
@bestander I will make some tests with my failing use case and a high network concurrency and get back to you on that then!

**Comment by mafintosh** [comment]
@victornoel yea, you're probably running out of file descriptors. Try using graceful-fs as mentioned. If that works we try handling out-of-fd's errors in the module

**Comment by victornoel** [comment]
@mafintosh @shinnn nope, it doesn't seem to change anything…
Would there be a way to be 100% sure it is the file descriptors? maybe via a setting to increase the available file descriptor number on my machine or something like that?

**Comment by mafintosh** [comment]
@victornoel you can bump your ulimit with the `ulimit` cli. try setting it to a high number and let me know if that still doesn't work

Also if you can gist a simple reproducible test case, I can probably fix it for you.

**Comment by victornoel** [comment]
@mafintosh raising the ulimit (`-n` right?) to 1000000 doesn't make the error disappear…

I will try to make a script reproducing this problem but I'm not familiar at all with writing this kind fo things in javascript actually… maybe @bestander if you could do it since you were proposing something? Thanks :)

**Comment by bestander** [comment]
I wish I had a moment to make a repro script.
The idea is to take it from Yarn https://github.com/yarnpkg/yarn/blob/master/src/fetchers/tarball-fetcher.js#L70 and run it in parallel and as input use a file reader

**Comment by victornoel** [comment]
@bestander it's the parallel aspect that I don't know how to do. Or could I run many node process in parallel and we will achieve the same situation?

**Comment by bestander** [comment]
Just run it in a regular for loop, JS will make those stream tasks in parallel

**Comment by victornoel** [comment]
ok, I'm on it :)

**Comment by victornoel** [comment]
I wrote that, that's not great but I can't make it crash...
```js
const tar = require('tar-fs');
const fs = require('fs');
const gm = require('gunzip-maybe');
const crypto = require('crypto');
const stream = require('stream');


class HashStream extends stream.Transform {
    constructor(options) {
        super(options);
        this._hash = crypto.createHash('sha1');
        this._updated = false;
    }

    _transform(chunk, encoding, callback) {
        this._updated = true;
        this._hash.update(chunk);
        callback(null, chunk);
    }

    getHash() {
        return this._hash.digest('hex');
    }
}

function create(i) {
    const vStream = new HashStream();

    fs.createReadStream('core-4.0.0-rc.1.tgz')
        .pipe(vStream);

    vStream
        .pipe(fs.createWriteStream('./tar/' + i))
        .on('error', e => console.log('1', e));

    vStream
        .pipe(gm())
        .pipe(tar.extract('./extract/' + i + '/', {
            strip: 1,
            dmode: 0o555, // all dirs should be readable
            fmode: 0o444, // all files should be readable
            chown: false, // don't chown. just leave as it is
        }))
        .on('error', e => console.log('2', e))
        .on('finish', () => {
            vStream.getHash();
        });
}

let i = 0;
while (i < 1000) {
    create(i);
    i++;
}
```

I even added the hash thing to see if it added some problems but no...

**Comment by bestander** [comment]
Thanks, it maybe something slightly different then.
Maybe a combination of multiple packages extracted at the same time.
Maybe something else incorrect is happening inside Yarn.

**Comment by victornoel** [comment]
Didn't think to try with different files, I did try with 100 times the same file copied and read in parallel, didn't change a thing.

**Comment by victornoel** [comment]
@bestander I continued to experiment by using `request` with the same kind of parameters and the remote url, then with an url hosted on my machine for it to arrive very fast.
None showed the problem.

Maybe this is coming to the queue thing that handle limited concurrency in yarn then? not sure why but who knows... concurrency is never easy ;)

**Comment by victornoel** [comment]
(also tried node 6 and 7)

**Comment by bestander** [comment]
This is a problem on Yarn's side https://github.com/yarnpkg/yarn/issues/2629#issuecomment-292753968.
Because of bug deduplication there are cases when the same .tgz file gets downloaded and extracted into the same destination in parallel.

Sorry for the troubles, I think this bug should be closed

**Comment by victornoel** [comment]
thanks!
