### ISSUE TITLE
problems while bundling with dependency on tar-fs

### ISSUE THREAD

**Issue by kanekotic** [mafintosh/tar-fs#62]
I am getting an issue form one of your sub dependencies `mkdirp`, it has a deprecated notation of 
```
mode = 0777 & (~process.umask());
```
this is solve on 0.5.1 ( https://github.com/substack/node-mkdirp/issues/98 ), would it be posible to update this dependency? i will open a PR for it later today.

I am using your pack in this project https://www.npmjs.com/package/any-prebuilt

**Comment by mafintosh** [comment]
I bumped mkdirp to 0.5.1 in 1.15.2 - Let me know if that helps you out

**Comment by kanekotic** [comment]
ok, will update dependency and test it on a moment, sorry for opening this issue.
