### ISSUE TITLE
exceptions during untar crash the application

### ISSUE THREAD

**Issue by michael-ts** [mafintosh/tar-fs#69]
Is it possible to have better error handling when extracting (or packing) or does it already exist?

For instance, if I try to extract a tarball containing filenames differing only in case onto a file-system that is only case-preserving, I can get exceptions in a number of different ways - for instance, if two files differ only in case and one is a file and the other is a directory, or if one of these files tries to be a symlink to the other.  I'm also concerned that other types of errors might occur which I simply haven't run into yet.

I have tried catching such errors using `process.on("uncaughtException",f)` but after the exception handler is run no more files are processed from the tarball.

Is there some kind of best practice for handling errors that I am missing, or is this a bug in tar-fs?

**Comment by mafintosh** [comment]
Have you tried attaching an error handler on the extract stream?

**Comment by michael-ts** [comment]
Oh, my bad... I have to return the fileStream... in other places it ``||`` against the original so this isn't necessary.

**Comment by michael-ts** [comment]
In any case, this isn't catching the first type of error, where it's attempting to untar a directory with a name that differs only in case from a previously extracted file.   I suspect catching errors on the fileStream will only work if there's an actual error extracting a file, not a directory or link?

**Comment by mafintosh** [comment]
you need to return a stream here.
