### ISSUE TITLE
Listening for end of extraction

### ISSUE THREAD

**Issue by RangerMauve** [mafintosh/tar-fs#7]
Hello, I'm wrapping tar.extract within a promise for my application, and I'm having a bit of trouble listening for the end of the extraction.

Here is the code I'm using, assume that it's wrapped within a promise and `resolve` and `reject` are defined and work properly. As well, `incoming` is an incoming file stream.

``` javascript
var extractor = tar.extract(folder);
incoming.on("error", reject);
extractor.on("error", reject);
extractor.on("end", resolve);
incoming.pipe(extractor);
```

**Comment by jfromaniello** [comment]
Is this still valid? It seems it doesn't emit neither finish, close nor end for me

**Comment by jfromaniello** [comment]
Ignore my previos message, it does work for me.

**Comment by eddiemonge** [comment]
Why not `'end'`?

**Comment by mafintosh** [comment]
@eddiemonge because writable streams in node only emit `finish`.
