### ISSUE TITLE
How to handle device nodes?

### ISSUE THREAD

**Issue by michael-ts** [mafintosh/tar-fs#71]
I'm using ts-far and am running into an issue where an exception is thrown when a device node is encountered in a tarball:

    Error: unsupported type for dev/dsp1 (character-device)

Looking at the code, it appears that tar-fs only knows how to handle normal files, directories, and symlinks.    It's not clear to me how to work around this so my program won't crash or improperly handle device nodes.

**Comment by mafintosh** [comment]
We could add an option to ignore those. PR welcome!
