### ISSUE TITLE
Make opts.dereference available in extract() too

### ISSUE THREAD

**Issue by Ekliptor** [mafintosh/tar-fs#73]
Hi,
I am using your tool in a script updating some node projects. This includes copying symlinks.
Your latest version fails unpacking bundles I packed with your tool because of line 337 in index.js

I see you have `opts.dereference` available in the `pack()` function to choose between stat and lstat.
Can you please make the sam available in `extract()` too?

Thanks
(I'm currently running a fork of your version, but seems overkill because of this minor change)

**Comment by mafintosh** [comment]
PR welcome :)
