### ISSUE TITLE
Can't use zlib.createGzip as transform in mapStream function

### ISSUE THREAD

**Issue by payitforwardnow** [mafintosh/tar-fs#75]
I'm using transforms in the mapStream function for each file. Several I've used work as expected; however, I'm unable to use zlib.createGzip as a transform. 
```
mapStream: function(fileStream, header) {
   var compressor = zlib.createGzip();
   return fileStream.pipe(compressor);
}
```

The following works
```
mapStream: function(fileStream, header) {
   var cipher = crypto.createCipher('aes-256-ctr', 'Thisisatest')
   return fileStream.pipe(cipher);
}
```

Am I missing something? I've also tried zlib.createDefate, zlib.createDefateRaw, and several other transforms without success.

Thank you in advance for your time and consideration.

**Comment by payitforwardnow** [comment]
Ok I think this is a duplicate of #42.

**Comment by payitforwardnow** [comment]
FYI - I found a solution to this using a different archive format. "tar" format has a lot of limitations so I decided to find/create a better solution. You can create of an archive of an entire directory and filter, compress and/or encrypt "on-the-fly:. One of the great things about this solution is that the archive is also random access so you can retrieve individual files without having to read in the entire archive. Each file can be compressed based on file type (or not) and can be encrypted using any encryption scheme you want with its own unique encryption key (if you prefer). Anyway if anyone is interested please let me know.

**Comment by blacksunset** [comment]
Help, still not woking

**Comment by mafintosh** [comment]
Yep, the mapStream has to have the same length or you need to update the size of the header in the same tick. added something to the readme about it.
