### ISSUE TITLE
emoji inside of files breaks the resulting tar.

### ISSUE THREAD

**Issue by valyrie97** [mafintosh/tar-fs#80]
Test case: put a single emoji in a plain text file, try to tar it. The resulting file will have written to it all files that it read before the emoji file, but stops writing afterwards.

I assume this is a more generic problem with alternate encodings, but the problem that my team just had was specific to emoji.

edit: also, not sure if this issue would be better opened in tar-stream, or one of this libraries' dependencies, let me know!

**Comment by mafintosh** [comment]
Can you check against latest and reopen if still an issue?
