### ISSUE TITLE
Add option to ignore missing files/stat errors

### ISSUE THREAD

**Issue by gramakri** [mafintosh/tar-fs#81]
If a file or directory goes missing during packing, there is no way to ignore the error. The use case is when arching a large directory structure which is "live". For example, when archiving a large mailbox directory, temporary files come and go, this module errors and there is no way handle to ignore them.

A possible hack for now is to create a custom xfs and return some magic stat objects that get ignored by the code but this is hard because it is hard to just override the "stat" function and also I cannot see a way to skip missing directories since that always errors.

To get the discussion going, I have created an option `ignoreStatError` (https://github.com/cloudron-io/tar-fs/commit/1ffd9bd1b131cad3a1cfdb4ea5014d89a70ee157). This works my use case atleast. But I am happy to fix this in whatever manner it will be accepted upstream. For example, maybe a custom function called ignoreStatError would be preferred like `ignore`.

**Comment by gramakri** [comment]
For comparison, the system tar command will put a warning saying "file removed when before we read it" but will continue to completion and exit with an error. The messages can be suppressed with [--warning](http://man7.org/linux/man-pages/man1/tar.1.html). Maybe we can add `ignoreFileRemoved` and specifically check for `ENOENT` in the error code and keep this false by default for backward compat. I like this better.

**Comment by gramakri** [comment]
I have made it an option called ignoreFileRemoved now - https://github.com/cloudron-io/tar-fs/tree/ignore_file_removed

**Comment by gramakri** [comment]
Any thoughts on this? I can submit a PR

**Comment by gramakri** [comment]
We use it like this:

```
    var pack = tar.pack('/', {
        ignoreStatError: (path, err) => {
            debug(`tarPack: error stat'ing ${path} - ${err.code}`);
            return err.code === 'ENOENT'; // ignore if file or dir got removed (probably some temporary file)
        },
     ....
```

**Comment by mafintosh** [comment]
PR welcome
