### ISSUE TITLE
Consider dropping mkdirp

### ISSUE THREAD

**Issue by fraxken** [mafintosh/tar-fs#84]
Hi,

Node.js implement a recursive mkdir since v10.12.0. I think it would be a good idea to remove the mkdirp package in a new major release (3.0.0) that focus on the current Node.js LTS (v10, v12 etc..). There is still time before Node 8 goes EOL but i prefer to get ahead :) 

I would be happy to help if required.

Best Regards,
Thomas

**Comment by childish-sambino** [comment]
Requesting it be dropped or upgraded. Currently seeing warnings during install of upstream lib:
```
warning keytar > prebuild-install > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning keytar > prebuild-install > tar-fs > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

Relates to https://github.com/prebuild/prebuild-install/issues/117

**Comment by mafintosh** [comment]
Will be a major bump as we still support Node.js 8.

**Comment by mafintosh** [comment]
PR welcome

**Comment by mafintosh** [comment]
Fixed in latest
