### ISSUE TITLE
npm pulls in different versions of tar-stream

### ISSUE THREAD

**Issue by AustinKerr42** [mafintosh/tar-fs#94]
I have two npm packages that use `tar-fs` which pulls in `tar-stream`. What's interesting is that both versions of `tar-fs` are 2.1.0, but different versions of `tar-stream` are being pulled in. Not sure if this is an issue with `tar-fs`, but I haven't been able to find a reason/solution anywhere else.

If you know why this might be happening please let me know. The motivation to have `tar-stream` resolve to 2.1.4 in both places is that 2.1.3 has a vulnerability in it's nested dependency that I want to avoid. Using 2.1.4 fixes that, and I would prefer not to edit the lock file manually to get around this as it is auto generated.

I have tried deleting the node_modules and lock file before install, running `npm update tar-stream`, and running `npm install --package-lock-only` to update the lock file based on 'package.json' with no luck.

```
$ npm ls tar-stream
project@1.2.0 /Users/akerr/Documents/GitHub/project
|-- chrome-aws-lambda@5.3.0
|  |-- lambdafs@2.0.0
|    |-- tar-fs@2.1.0
|      |-- tar-stream@2.1.3
|-- puppeteer-core@5.3.0
|  |-- tar-fs@2.1.0
|    |-- tar-stream@2.1.4
```

**Comment by Jowze** [comment]
Hello! I'm running into the same issue, it seems that tar-fs should use tar-stream 2.1.4 to fix the BL package dependency issue. I haven't been able to find a workaround to force tar-stream to version 2.1.4 in package-lock either

**Comment by mafintosh** [comment]
sounds like an npm issue?

**Comment by Jowze** [comment]
It could be, but I'm not sure how to fix it. For now I'm applying a workaround using the npm-force-resolutions package. Adding
 ```
"resolutions": {
    "tar-stream": "2.1.4"
  }

```
To package.json as well as 
```
 "preinstall": "npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions",
``` 
This way the "high severity vulnerability" warning shows on first install and then "tar-fs" ''tar-stream" dependency gets fixed in package-lock.json

**Comment by mafintosh** [comment]
latest has a force bump on tar-stream, maybe that helps
