### ISSUE TITLE
tar-fs is 2.5x slower than node-tar at decompressing?

### ISSUE THREAD

**Issue by Jarred-Sumner** [mafintosh/tar-fs#99]
I was looking at different libraries for untar'ing files and I came across this one. I saw your benchmark and got excited, so I wanted to see what it would look like with just decompressing.

You can reproduce this here https://github.com/Jarred-Sumner/tar-fs-vs-node-tar-bench.

`tar-fs` results:

```zsh
❯ time node tar-fs-run.js
________________________________________________________
Executed in    1.16 secs   fish           external
   usr time  831.99 millis  137.00 micros  831.85 millis
   sys time  641.63 millis  711.00 micros  640.92 millis
```

`node-tar` results:

```zsh
❯ time node  node-tar-run.js
Executed in  476.10 millis    fish           external
   usr time  492.58 millis  112.00 micros  492.46 millis
   sys time  371.90 millis  623.00 micros  371.28 millis
```

Did I mess something up in the benchmark? Or maybe the benchmark on the README targeting an older version of `node-tar`?

**Comment by mafintosh** [comment]
prop using an old version, updating in next version
